In [1]:
import numpy as np

In [12]:
# 10個のfloat32の0を生成
v = np.zeros(10, dtype=np.float32)
print(v)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [13]:
# 10個のfloat32の0~nを生成
v = np.arange(10, dtype=np.float32)
print(v)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [15]:
# vに3をかける
v *= 3
print(v)

[  0.   9.  18.  27.  36.  45.  54.  63.  72.  81.]


In [16]:
print(v.mean())

40.5
